### ISSUE TITLE
Displayed when an exception is encountered

### ISSUE THREAD

**Issue by kerwinxu** [fluisgirardi/pascalscada#7]
SerialPortDriver1 -> ModBusRTUDriver1 -> PLCTagNumber1 -> HMILabel1 .
It can be work , but when com1 is error , for example : other program use this com1 .
my code is below :
try
SerialPortDriver1.ComPort := cbbComName1.Text
except
on E:Exception do  
begin
PLCTagNumber1.AutoRead := False; 
PLCTagNumber1.Write(-1);
end;
end;

PLCTagNumber1 always show last number , not 0.0 or -1 ;
why ?

**Comment by fluisgirardi** [comment]
Hi!

On next issues, create it on https://github.com/fluisgirardi/pascalscada_v0

I have plans to draw on each control linked with tags in communication error state a warning /!\ icon, like others scada systems.

I don´t replace the tag value by zero or other value, because they can be valid values on a normal situation. On code, you can always check tag.LastAsyncReadStatus to check communication state.

**Comment by kerwinxu** [comment]
> Hi!
> 
> On next issues, create it on https://github.com/fluisgirardi/pascalscada_v0
> 
> I have plans to draw on each control linked with tags in communication error state a warning /!\ icon, like others scada systems.
> 
> I don´t replace the tag value by zero or other value, because they can be valid values on a normal situation. On code, you can always check tag.LastAsyncReadStatus to check communication state.

Thank you .
